hello world started

diff --git a/11-functions b/11-functions
--- a/11-functions
+++ b/11-functions
@@ -2,10 +2,10 @@
 USERID=$(id -u)
 if [ $USERID -ne 0 ]
 then
- echo "ERROR::Please run the script with root access"
- exit1 #given other than 0 upto 127
- else
- echo "your running with root acccess"
+    echo "ERROR::Please run the script with root access"
+    exit1 #given other than 0 upto 127
+else
+    echo "your running with root acccess"
 fi
 
 #validate function takes input as exit status what command they tried to install
@@ -23,11 +23,11 @@ VALIDATE(){
 dnf list installed mysql
 if [ $? -ne 0 ]
 then
-    echo "MYSQL is not installed going... to installed"
+    echo "MYSQL is not installed going... to installed it"
     dnf install MYSQL -y
     VALIDATE $? "MysQL"
 else
-    echo " MYSQL is already  installed... nothing to do"
+    echo " MYSQL is already  installed... Nothing to do"
 fi
 
 dnf list installed python3
@@ -35,7 +35,7 @@ if [ $? -ne 0 ]
 then
     echo "python is not installed going to installed"
     dnf install phython3 -y
-    VALIDATE $? "phython3"
+    VALIDATE $? "python3"
 else
     echo "python3 is alredy installed nothong...to do"
 fi
@@ -47,5 +47,5 @@ then
     dnf installed ngnix -y
     VALIDATE $? "nginx"
 else
-    echo "nginx already installed Nothing...to do"
+    echo "nginx already installed...Nothing to do"
 fi
